#!/usr/bin/env python3
"""
Auto-Code Documenter
Generates documentation for GitHub repositories automatically.
"""

import os
import json
import subprocess
from pathlib import Path
from typing import Dict, List, Optional


class AutoDocGenerator:
    """Automatically generate documentation for code repositories."""
    
    SUPPORTED_EXTENSIONS = {
        '.py': 'Python',
        '.js': 'JavaScript',
        '.ts': 'TypeScript',
        '.java': 'Java',
        '.go': 'Go',
        '.rs': 'Rust',
        '.cpp': 'C++',
        '.c': 'C',
        '.rb': 'Ruby',
        '.php': 'PHP',
    }
    
    def __init__(self, repo_path: str):
        self.repo_path = Path(repo_path)
        self.structure = {}
        
    def scan_repository(self) -> Dict:
        """Scan repository structure and return file tree."""
        self.structure = {'files': [], 'dirs': []}
        
        for root, dirs, files in os.walk(self.repo_path):
            # Skip hidden and common non-doc directories
            dirs[:] = [d for d in dirs if not d.startswith('.') and d not in ['node_modules', '__pycache__', 'venv']]
            
            rel_path = os.path.relpath(root, self.repo_path)
            
            for file in files:
                if not file.startswith('.'):
                    file_path = os.path.join(root, file)
                    ext = Path(file).suffix
                    self.structure['files'].append({
                        'path': file_path,
                        'name': file,
                        'extension': ext,
                        'language': self.SUPPORTED_EXTENSIONS.get(ext, 'Unknown')
                    })
                    
        return self.structure
    
    def generate_readme(self) -> str:
        """Generate a README.md based on repository structure."""
        readme = f"""# {self.repo_path.name}

## Repository Structure

This repository contains {len(self.structure['files'])} files.

### Files

"""
        
        # Group by extension
        by_ext = {}
        for f in self.structure['files']:
            ext = f['extension'] or 'No extension'
            if ext not in by_ext:
                by_ext[ext] = []
            by_ext[ext].append(f['name'])
        
        for ext, files in sorted(by_ext.items()):
            readme += f"#### {ext} files ({len(files)})\n"
            for f in files[:5]:  # Show first 5
                readme += f"- `{f}`\n"
            if len(files) > 5:
                readme += f"- ... and {len(files) - 5} more\n"
            readme += "\n"
            
        readme += """---

*Auto-generated by Alita's Auto-Code Documenter*
"""
        return readme
    
    def run(self):
        """Run the documentation generator."""
        print(f"Scanning repository: {self.repo_path}")
        self.scan_repository()
        print(f"Found {len(self.structure['files'])} files")
        
        readme_content = self.generate_readme()
        print("\n" + "="*50)
        print("GENERATED README:")
        print("="*50)
        print(readme_content)
        
        return readme_content


if __name__ == "__main__":
    import sys
    repo_path = sys.argv[1] if len(sys.argv) > 1 else "."
    generator = AutoDocGenerator(repo_path)
    generator.run()
